testname: MSS Subjective Evaluation
testId: mss
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: consent
      id: informed_consent
      name: Informed Consent
      mustConsent: true
      content: consent content here

    - type: generic
      id: welcome_instructions
      name: Welcome to the musical source separation (MSS) evaluation task
      content: "Thank you for taking part in this study as the part of my Master’s thesis at the University of Amsterdam.<br>
        In this research, we will be performing an informal MUSHRA experiment to correlate subjective score of audio quality with objective measures. In musical source separation (MSS), an audio recording is broken into its constituent parts (eg: guitar, singing, drums, bass). These extractions can have varying qualities as measured objectively and subjectively—at odds with similar extractions. In other words, some extractions can have a high objective score and sound terrible, but others can have the opposite.<br>
        In this experiment, you will hear approximately 25 different audio samples. The samples are of individual instruments (eg: guitar, drums, bass, or vocals). A reference (perfect 100 score) will be provided. In this test, please rate the other recordings from 0 (unintelligible, or complete task failure) to 100. The task should take approximately 15 minutes.<br>
        <br>
        <br>
        Please use your computer at a reasonable volume with headphones in a quiet listening environment.<br>
        When evaluating these extracts, compare them to the reference, which would warrant a 100% score. <br> Pay particular attention to whether the extract has other instruments that should not be present, interference, or noise. These should negatively affect the score. <br>
        Thanks, Noah Jaffe"

    - type: mushra
      id: trial1
      name: MUSHRA
      content: This exercise is to evaluate the quality of a vocal audio extraction.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/1/ref_10s.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/1/2dft_10s.wav
          C2: configs/resources/audio/1/hplp_10s.wav
          C3: configs/resources/audio/1/irm2_10s.wav
          C4: configs/resources/audio/1/rep2_10s.wav
          C5: configs/resources/audio/1/tau1_10s.wav

    - type: mushra
      id: trial2
      name: MUSHRA
      content: This exercise is to evaluate the quality of a vocal accompaniment extraction. A successful extract for this task contains no singing. Consider whether this extraction could be used for karaoke or a cover recording.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/2/ref_10s.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/2/2dft_10s.wav
          C2: configs/resources/audio/2/hplp_10s.wav
          C3: configs/resources/audio/2/irm2_10s.wav
          C4: configs/resources/audio/2/rep2_10s.wav
          C5: configs/resources/audio/2/tau1_10s.wav

    - type: mushra
      id: trial3
      name: MUSHRA
      content: This exercise is to evaluate the quality of a rock band accompaniment extraction. A successful extract for this task contains no singing. Consider whether this extraction could be used for karaoke or a cover recording.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/3/ref_10s.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/3/2DFT_10s.wav
          C2: configs/resources/audio/3/HPLP_10s.wav
          C3: configs/resources/audio/3/IRM2_10s.wav
          C4: configs/resources/audio/3/REP2_10s.wav
          C5: configs/resources/audio/3/TAU1_10s.wav

    - type: mushra
      id: trial4
      name: MUSHRA
      content: This exercise is to evaluate the quality of a guitar extraction. Consider whether this extraction could be used as a sample for a new song or remix.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/4/ref_10s.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/4/IRM2_10s.wav
          C2: configs/resources/audio/4/MWF_10s.wav
          C3: configs/resources/audio/4/TAU1_10s.wav
          C4: configs/resources/audio/4/UHL3_10s.wav

    - type: mushra
      id: trial5
      name: MUSHRA
      content: This exercise is to evaluate the quality of a drums extraction. Consider whether this extraction could be used as a sample for a new song or remix.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/5/ref_10s.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/5/IRM2_10s.wav
          C2: configs/resources/audio/5/MWF_10s.wav
          C3: configs/resources/audio/5/TAU1_10s.wav
          C4: configs/resources/audio/5/UHL3_10s.wav

    - type: finish
      name: Thank you
      content: Thank you for participating!
      showResults: true
      writeResults: true
