bufferSize: 2048
pages:
- content: Instructions for Participants<br><br>Thank you for joining this study at the University of Amsterdam.<br><br>This research examines how subjective audio quality ratings align with objective measurements in musical source separation (MSS)—the process of isolating instruments (e.g., guitar, vocals, drums, bass) from a mix.<br><br><b>Task Overview</b><br>- You will complete <b>10 tasks</b> (~15 minutes).<br>- Each task involves rating an isolated instrument track on a scale from <b>0 to 100</b>:<br>  - <b>100</b> = Perfect match to the reference<br>  - <b>0</b> = Unintelligible or complete failure<br><br><b>What to Listen For</b><br>- Unwanted sounds (e.g., other instruments leaking in)<br>- Distortions or artifacts<br>- Clarity and naturalness<br><br><b>Test Setup</b><br>- Use a <b>computer</b> with <b>headphones</b>.<br>- Find a <b>quiet</b> space.<br><br>Thank you!<br><b>Noah Jaffe</b>
  id: welcome_instructions
  name: Welcome to the musical source separation (MSS) evaluation task
  type: generic
- content: You will be participating in this research project on a voluntary basis. This means you are free to stop taking part at any stage. This will not have any consequences and you will not be obliged to finish the procedures described above. You can always decide to withdraw your consent later on. If you decide to stop or withdraw your consent, all the information gathered up until then will be permanently deleted.<br>I hereby declare that I have been clearly informed about the research project musical source separation perception at the University of Amsterdam, Faculty of Humanities, conducted by Noah Jaffe under supervision of J. A. Burgoyne as described in the information brochure. My questions have been answered to my satisfaction.<br>I realise that participation in this research is on an entirely voluntary basis. I retain the right to revoke this consent without having to provide any reasons for my decision. I am aware that I am entitled to discontinue the research at any time,
    and that I can always withdraw my consent after the research has ended. If I decide to stop or withdraw my consent, all the information gathered up until then will be permanently deleted.<br>I understand that no personal information will be collected.<br>If I need any further information on the research, now or in the future, I can contact J.A. Burgoyne (phone number +31 20 525 7034 e-mail j.a.burgoyne@uva.nl; Postbus 93058, 1099 BB Amsterdam.<br>If I have any complaints regarding this research, I can contact the secretary of the Ethics Committee of the Faculty of Humanities of the University of Amsterdam; email commissie- ethiek-fgw@uva.nl; phone number +31 20 525 3054; Kloveniersburgwal 48, 1012 CX Amsterdam.<br>By pressing Next I consent to participating in this research. Furthermore, I understand that I can revoke my consent by closing the web browser at any time prior to pressing Send Results on the final page.
  id: informed_consent
  mustConsent: true
  name: Informed Consent
  type: generic
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: The Doppler Shift - Atrophy__other
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/The Doppler Shift - Atrophy__other/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/The Doppler Shift - Atrophy__other/IRM1.wav
    Open-UMix: configs/resources/audio/The Doppler Shift - Atrophy__other/Open-UMix.wav
    SCNet-large: configs/resources/audio/The Doppler Shift - Atrophy__other/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/The Doppler Shift - Atrophy__other/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/The Doppler Shift - Atrophy__other/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Signe Jakobsen - What Have You Done To Me__other
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Signe Jakobsen - What Have You Done To Me__other/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Signe Jakobsen - What Have You Done To Me__other/IRM1.wav
    Open-UMix: configs/resources/audio/Signe Jakobsen - What Have You Done To Me__other/Open-UMix.wav
    SCNet-large: configs/resources/audio/Signe Jakobsen - What Have You Done To Me__other/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Signe Jakobsen - What Have You Done To Me__other/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Signe Jakobsen - What Have You Done To Me__other/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Cristina Vane - So Easy__other
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Cristina Vane - So Easy__other/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Cristina Vane - So Easy__other/IRM1.wav
    Open-UMix: configs/resources/audio/Cristina Vane - So Easy__other/Open-UMix.wav
    SCNet-large: configs/resources/audio/Cristina Vane - So Easy__other/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Cristina Vane - So Easy__other/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Cristina Vane - So Easy__other/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Juliet's Rescue - Heartbeats__other
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Juliet's Rescue - Heartbeats__other/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Juliet's Rescue - Heartbeats__other/IRM1.wav
    Open-UMix: configs/resources/audio/Juliet's Rescue - Heartbeats__other/Open-UMix.wav
    SCNet-large: configs/resources/audio/Juliet's Rescue - Heartbeats__other/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Juliet's Rescue - Heartbeats__other/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Juliet's Rescue - Heartbeats__other/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Enda Reilly - Cur An Long Ag Seol__other
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Enda Reilly - Cur An Long Ag Seol__other/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Enda Reilly - Cur An Long Ag Seol__other/IRM1.wav
    Open-UMix: configs/resources/audio/Enda Reilly - Cur An Long Ag Seol__other/Open-UMix.wav
    SCNet-large: configs/resources/audio/Enda Reilly - Cur An Long Ag Seol__other/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Enda Reilly - Cur An Long Ag Seol__other/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Enda Reilly - Cur An Long Ag Seol__other/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Motor Tapes - Shore__other
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Motor Tapes - Shore__other/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Motor Tapes - Shore__other/IRM1.wav
    Open-UMix: configs/resources/audio/Motor Tapes - Shore__other/Open-UMix.wav
    SCNet-large: configs/resources/audio/Motor Tapes - Shore__other/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Motor Tapes - Shore__other/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Motor Tapes - Shore__other/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Mu - Too Bright__other
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Mu - Too Bright__other/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Mu - Too Bright__other/IRM1.wav
    Open-UMix: configs/resources/audio/Mu - Too Bright__other/Open-UMix.wav
    SCNet-large: configs/resources/audio/Mu - Too Bright__other/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Mu - Too Bright__other/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Mu - Too Bright__other/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Louis Cressy Band - Good Time__other
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Louis Cressy Band - Good Time__other/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Louis Cressy Band - Good Time__other/IRM1.wav
    Open-UMix: configs/resources/audio/Louis Cressy Band - Good Time__other/Open-UMix.wav
    SCNet-large: configs/resources/audio/Louis Cressy Band - Good Time__other/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Louis Cressy Band - Good Time__other/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Louis Cressy Band - Good Time__other/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Speak Softly - Broken Man__other
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Speak Softly - Broken Man__other/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Speak Softly - Broken Man__other/IRM1.wav
    Open-UMix: configs/resources/audio/Speak Softly - Broken Man__other/Open-UMix.wav
    SCNet-large: configs/resources/audio/Speak Softly - Broken Man__other/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Speak Softly - Broken Man__other/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Speak Softly - Broken Man__other/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: The Easton Ellises - Falcon 69__other
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/The Easton Ellises - Falcon 69__other/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/The Easton Ellises - Falcon 69__other/IRM1.wav
    Open-UMix: configs/resources/audio/The Easton Ellises - Falcon 69__other/Open-UMix.wav
    SCNet-large: configs/resources/audio/The Easton Ellises - Falcon 69__other/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/The Easton Ellises - Falcon 69__other/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/The Easton Ellises - Falcon 69__other/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Side Effects Project - Sing With Me__other
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Side Effects Project - Sing With Me__other/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Side Effects Project - Sing With Me__other/IRM1.wav
    Open-UMix: configs/resources/audio/Side Effects Project - Sing With Me__other/Open-UMix.wav
    SCNet-large: configs/resources/audio/Side Effects Project - Sing With Me__other/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Side Effects Project - Sing With Me__other/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Side Effects Project - Sing With Me__other/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Georgia Wonder - Siren__other
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Georgia Wonder - Siren__other/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Georgia Wonder - Siren__other/IRM1.wav
    Open-UMix: configs/resources/audio/Georgia Wonder - Siren__other/Open-UMix.wav
    SCNet-large: configs/resources/audio/Georgia Wonder - Siren__other/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Georgia Wonder - Siren__other/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Georgia Wonder - Siren__other/lpf_anchor.wav
  type: mushra
- content: Thank you for participating in this listening test. Please click the button below to submit your responses.
  name: Thank you
  showResults: true
  type: finish
  writeResults: true
remoteService: service/write.php
showButtonPreviousPage: true
stopOnErrors: true
testId: mss
testname: MSS Subjective Evaluation
