bufferSize: 2048
pages:
- content: Instructions for Participants<br><br>Thank you for joining this study at the University of Amsterdam.<br><br>This research examines how subjective audio quality ratings align with objective measurements in musical source separation (MSS)—the process of isolating instruments (e.g., guitar, vocals, drums, bass) from a mix.<br><br><b>Task Overview</b><br>- You will complete <b>30 tasks</b> (~45 minutes).<br>- Each task involves rating an isolated instrument track on a scale from <b>0 to 100</b>:<br>  - <b>100</b> = Perfect match to the reference<br>  - <b>0</b> = Unintelligible or complete failure<br><br><b>What to Listen For</b><br>- Unwanted sounds (e.g., other instruments leaking in)<br>- Distortions or artifacts<br>- Clarity and naturalness<br><br><b>Test Setup</b><br>- Use a <b>computer</b> with <b>headphones</b>.<br>- Find a <b>quiet</b> space.<br><br>Thank you!<br><b>Noah Jaffe</b>
  id: welcome_instructions
  name: Welcome to the musical source separation (MSS) evaluation task
  type: generic
- content: You will be participating in this research project on a voluntary basis. This means you are free to stop taking part at any stage. This will not have any consequences and you will not be obliged to finish the procedures described above. You can always decide to withdraw your consent later on. If you decide to stop or withdraw your consent, all the information gathered up until then will be permanently deleted.<br>I hereby declare that I have been clearly informed about the research project musical source separation perception at the University of Amsterdam, Faculty of Humanities, conducted by Noah Jaffe under supervision of J. A. Burgoyne as described in the information brochure. My questions have been answered to my satisfaction.<br>I realise that participation in this research is on an entirely voluntary basis. I retain the right to revoke this consent without having to provide any reasons for my decision. I am aware that I am entitled to discontinue the research at any time,
    and that I can always withdraw my consent after the research has ended. If I decide to stop or withdraw my consent, all the information gathered up until then will be permanently deleted.<br>I understand that no personal information will be collected.<br>If I need any further information on the research, now or in the future, I can contact J.A. Burgoyne (phone number +31 20 525 7034 e-mail j.a.burgoyne@uva.nl; Postbus 93058, 1099 BB Amsterdam.<br>If I have any complaints regarding this research, I can contact the secretary of the Ethics Committee of the Faculty of Humanities of the University of Amsterdam; email commissie- ethiek-fgw@uva.nl; phone number +31 20 525 3054; Kloveniersburgwal 48, 1012 CX Amsterdam.<br>By pressing Next I consent to participating in this research. Furthermore, I understand that I can revoke my consent by closing the web browser at any time prior to pressing Send Results on the final page.
  id: informed_consent
  mustConsent: true
  name: Informed Consent
  type: generic
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Buitraker - Revo X__drums
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/196/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/196/IRM1.wav
    Open-UMix: configs/resources/audio/196/Open-UMix.wav
    SCNet-large: configs/resources/audio/196/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/196/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/196/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Tom McKenzie - Directions__drums
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/66/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/66/IRM1.wav
    Open-UMix: configs/resources/audio/66/Open-UMix.wav
    SCNet-large: configs/resources/audio/66/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/66/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/66/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Georgia Wonder - Siren__drums
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/80/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/80/IRM1.wav
    Open-UMix: configs/resources/audio/80/Open-UMix.wav
    SCNet-large: configs/resources/audio/80/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/80/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/80/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Motor Tapes - Shore__drums
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/110/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/110/IRM1.wav
    Open-UMix: configs/resources/audio/110/Open-UMix.wav
    SCNet-large: configs/resources/audio/110/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/110/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/110/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: The Mountaineering Club - Mallory__drums
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/149/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/149/IRM1.wav
    Open-UMix: configs/resources/audio/149/Open-UMix.wav
    SCNet-large: configs/resources/audio/149/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/149/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/149/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Girls Under Glass - We Feel Alright__drums
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/185/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/185/IRM1.wav
    Open-UMix: configs/resources/audio/185/Open-UMix.wav
    SCNet-large: configs/resources/audio/185/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/185/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/185/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Side Effects Project - Sing With Me__drums
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/30/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/30/IRM1.wav
    Open-UMix: configs/resources/audio/30/Open-UMix.wav
    SCNet-large: configs/resources/audio/30/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/30/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/30/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Detsky Sad - Walkie Talkie__drums
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/35/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/35/IRM1.wav
    Open-UMix: configs/resources/audio/35/Open-UMix.wav
    SCNet-large: configs/resources/audio/35/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/35/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/35/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: We Fell From The Sky - Not You__drums
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/94/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/94/IRM1.wav
    Open-UMix: configs/resources/audio/94/Open-UMix.wav
    SCNet-large: configs/resources/audio/94/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/94/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/94/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Secretariat - Borderline__drums
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/181/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/181/IRM1.wav
    Open-UMix: configs/resources/audio/181/Open-UMix.wav
    SCNet-large: configs/resources/audio/181/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/181/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/181/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Louis Cressy Band - Good Time__drums
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/12/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/12/IRM1.wav
    Open-UMix: configs/resources/audio/12/Open-UMix.wav
    SCNet-large: configs/resources/audio/12/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/12/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/12/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: The Long Wait - Dark Horses__drums
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/98/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/98/IRM1.wav
    Open-UMix: configs/resources/audio/98/Open-UMix.wav
    SCNet-large: configs/resources/audio/98/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/98/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/98/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Juliet's Rescue - Heartbeats__drums
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/7/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/7/IRM1.wav
    Open-UMix: configs/resources/audio/7/Open-UMix.wav
    SCNet-large: configs/resources/audio/7/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/7/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/7/lpf_anchor.wav
  type: mushra
- content: Thank you for participating in this listening test. Please click the button below to submit your responses.
  name: Thank you
  showResults: true
  type: finish
  writeResults: true
remoteService: service/write.php
showButtonPreviousPage: true
stopOnErrors: true
testId: mss
testname: MSS Subjective Evaluation
