- content: "Thank you for taking part in this study as the part of my Master\u2019\
    s thesis at the University of Amsterdam.<br> In this research, we will be performing\
    \ an informal MUSHRA experiment to correlate subjective score of audio quality\
    \ with objective measures. In musical source separation (MSS), an audio recording\
    \ is broken into its constituent parts (eg: guitar, singing, drums, bass). These\
    \ extractions can have varying qualities as measured objectively and subjectively\u2014\
    at odds with similar extractions. In other words, some extractions can have a\
    \ high objective score and sound terrible, but others can have the opposite.<br>\
    \ In this experiment, you will hear approximately 25 different audio samples.\
    \ The samples are of individual instruments (eg: guitar, drums, bass, or vocals).\
    \ A reference (perfect 100 score) will be provided. In this test, please rate\
    \ the other recordings from 0 (unintelligible, or complete task failure) to 100.\
    \ The task should take approximately 15 minutes.<br> <br> <br> Please use your\
    \ computer at a reasonable volume with headphones in a quiet listening environment.<br>\
    \ When evaluating these extracts, compare them to the reference, which would warrant\
    \ a 100% score. <br> Pay particular attention to whether the extract has other\
    \ instruments that should not be present, interference, or noise. These should\
    \ negatively affect the score. <br> Thanks, Noah Jaffe"
  id: welcome_instructions
  name: Welcome to the musical source separation (MSS) evaluation task
  type: generic
- content: " You will be participating in this research project on a voluntary basis.\
    \ This means you are free to stop taking part at any stage. This will not have\
    \ any consequences and you will not be obliged to finish the procedures described\
    \ above. You can always decide to withdraw your consent later on. If you decide\
    \ to stop or withdraw your consent, all the information gathered up until then\
    \ will be permanently deleted.<br> I hereby declare that I have been clearly informed\
    \ about the research project musical source separation perception at the University\
    \ of Amsterdam, Faculty of Humanities, conducted by Jaffe under supervision of\
    \ J. A. Burgoyne as described in the information brochure. My questions have been\
    \ answered to my satisfaction.<br> I realise that participation in this research\
    \ is on an entirely voluntary basis. I retain the right to revoke this consent\
    \ without having to provide any reasons for my decision. I am aware that I am\
    \ entitled to discontinue the research at any time, and that I can always withdraw\
    \ my consent after the research has ended. If I decide to stop or withdraw my\
    \ consent, all the information gathered up until then will be permanently deleted.<br>\
    \ I understand that no personal information will be collected.<br> If I need any\
    \ further information on the research, now or in the future, I can contact J.A.\
    \ Burgoyne (phone number: +31 20 \u2013 525 7034 e-mail: j.a.burgoyne@uva.nl;\
    \ Postbus 93058, 1099 BB Amsterdam.<br> If I have any complaints regarding this\
    \ research, I can contact the secretary of the Ethics Committee of the Faculty\
    \ of Humanities of the University of Amsterdam; email: commissie- ethiek-fgw@uva.nl;\
    \ phone number: +31 20 \u2013 525 3054; Kloveniersburgwal 48, 1012 CX Amsterdam.<br>\
    \ By pressing Next I consent to participating in this research. Furthermore, I\
    \ understand that I can revoke my consent by closing the web browser at any time\
    \ prior to pressing \u201CSend Results\u201D on the final page."
  id: informed_consent
  mustConsent: true
  name: Informed Consent
  type: generic
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio
    estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial4
  name: MUSHRA
  reference: configs/resources/audio/trial4/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial4/TAU1.wav
    C2: configs/resources/audio/trial4/IRM2.wav
    C3: configs/resources/audio/trial4/MWF.wav
    C4: configs/resources/audio/trial4/UHL3.wav
  type: mushra
- content: This exercise is to evaluate the quality of a vocals audio estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial9
  name: MUSHRA
  reference: configs/resources/audio/trial9/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial9/TAU1.wav
    C2: configs/resources/audio/trial9/IRM2.wav
    C3: configs/resources/audio/trial9/MWF.wav
    C4: configs/resources/audio/trial9/UHL3.wav
    C5: configs/resources/audio/trial9/TAK2.wav
    C6: configs/resources/audio/trial9/2DFT.wav
  type: mushra
- content: This exercise is to evaluate the quality of a accomp audio estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial14
  name: MUSHRA
  reference: configs/resources/audio/trial14/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial14/TAU1.wav
    C2: configs/resources/audio/trial14/IRM2.wav
    C3: configs/resources/audio/trial14/MWF.wav
    C4: configs/resources/audio/trial14/UHL3.wav
    C5: configs/resources/audio/trial14/TAK2.wav
  type: mushra
- content: This exercise is to evaluate the quality of a accomp audio estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial19
  name: MUSHRA
  reference: configs/resources/audio/trial19/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial19/TAU1.wav
    C2: configs/resources/audio/trial19/IRM2.wav
    C3: configs/resources/audio/trial19/MWF.wav
    C4: configs/resources/audio/trial19/UHL3.wav
    C5: configs/resources/audio/trial19/TAK2.wav
  type: mushra
- content: This exercise is to evaluate the quality of a bass audio estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial24
  name: MUSHRA
  reference: configs/resources/audio/trial24/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial24/TAU1.wav
    C2: configs/resources/audio/trial24/IRM2.wav
    C3: configs/resources/audio/trial24/MWF.wav
    C4: configs/resources/audio/trial24/UHL3.wav
    C5: configs/resources/audio/trial24/TAK2.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial29
  name: MUSHRA
  reference: configs/resources/audio/trial29/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial29/TAU1.wav
    C2: configs/resources/audio/trial29/IRM2.wav
    C3: configs/resources/audio/trial29/MWF.wav
    C4: configs/resources/audio/trial29/UHL3.wav
    C5: configs/resources/audio/trial29/TAK2.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial34
  name: MUSHRA
  reference: configs/resources/audio/trial34/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial34/TAU1.wav
    C2: configs/resources/audio/trial34/IRM2.wav
    C3: configs/resources/audio/trial34/MWF.wav
    C4: configs/resources/audio/trial34/UHL3.wav
    C5: configs/resources/audio/trial34/TAK2.wav
  type: mushra
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio
    estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial39
  name: MUSHRA
  reference: configs/resources/audio/trial39/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial39/TAU1.wav
    C2: configs/resources/audio/trial39/IRM2.wav
    C3: configs/resources/audio/trial39/MWF.wav
    C4: configs/resources/audio/trial39/UHL3.wav
    C5: configs/resources/audio/trial39/TAK2.wav
  type: mushra
