bufferSize: 2048
pages:
- content: Instructions for Participants<br><br>Thank you for joining this study at the University of Amsterdam.<br><br>This research examines how subjective audio quality ratings align with objective measurements in musical source separation (MSS)—the process of isolating instruments (e.g., guitar, vocals, drums, bass) from a mix.<br><br><b>Task Overview</b><br>- You will complete <b>10 tasks</b> (~15 minutes).<br>- Each task involves rating an isolated instrument track on a scale from <b>0 to 100</b>:<br>  - <b>100</b> = Perfect match to the reference<br>  - <b>0</b> = Unintelligible or complete failure<br><br><b>What to Listen For</b><br>- Unwanted sounds (e.g., other instruments leaking in)<br>- Distortions or artifacts<br>- Clarity and naturalness<br><br><b>Test Setup</b><br>- Use a <b>computer</b> with <b>headphones</b>.<br>- Find a <b>quiet</b> space.<br><br>Thank you!<br><b>Noah Jaffe</b>
  id: welcome_instructions
  name: Welcome to the musical source separation (MSS) evaluation task
  type: generic
- content: You will be participating in this research project on a voluntary basis. This means you are free to stop taking part at any stage. This will not have any consequences and you will not be obliged to finish the procedures described above. You can always decide to withdraw your consent later on. If you decide to stop or withdraw your consent, all the information gathered up until then will be permanently deleted.<br>I hereby declare that I have been clearly informed about the research project musical source separation perception at the University of Amsterdam, Faculty of Humanities, conducted by Noah Jaffe under supervision of J. A. Burgoyne as described in the information brochure. My questions have been answered to my satisfaction.<br>I realise that participation in this research is on an entirely voluntary basis. I retain the right to revoke this consent without having to provide any reasons for my decision. I am aware that I am entitled to discontinue the research at any time,
    and that I can always withdraw my consent after the research has ended. If I decide to stop or withdraw my consent, all the information gathered up until then will be permanently deleted.<br>I understand that no personal information will be collected.<br>If I need any further information on the research, now or in the future, I can contact J.A. Burgoyne (phone number +31 20 525 7034 e-mail j.a.burgoyne@uva.nl; Postbus 93058, 1099 BB Amsterdam.<br>If I have any complaints regarding this research, I can contact the secretary of the Ethics Committee of the Faculty of Humanities of the University of Amsterdam; email commissie- ethiek-fgw@uva.nl; phone number +31 20 525 3054; Kloveniersburgwal 48, 1012 CX Amsterdam.<br>By pressing Next I consent to participating in this research. Furthermore, I understand that I can revoke my consent by closing the web browser at any time prior to pressing Send Results on the final page.
  id: informed_consent
  mustConsent: true
  name: Informed Consent
  type: generic
- content: This exercise is to evaluate the quality of a vocals audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Speak Softly - Broken Man__vocals
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Speak Softly - Broken Man__vocals/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Speak Softly - Broken Man__vocals/IRM1.wav
    Open-UMix: configs/resources/audio/Speak Softly - Broken Man__vocals/Open-UMix.wav
    REP1: configs/resources/audio/Speak Softly - Broken Man__vocals/REP1.wav
    SCNet-large: configs/resources/audio/Speak Softly - Broken Man__vocals/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Speak Softly - Broken Man__vocals/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Speak Softly - Broken Man__vocals/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a vocals audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Secretariat - Borderline__vocals
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Secretariat - Borderline__vocals/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Secretariat - Borderline__vocals/IRM1.wav
    Open-UMix: configs/resources/audio/Secretariat - Borderline__vocals/Open-UMix.wav
    REP1: configs/resources/audio/Secretariat - Borderline__vocals/REP1.wav
    SCNet-large: configs/resources/audio/Secretariat - Borderline__vocals/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Secretariat - Borderline__vocals/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Secretariat - Borderline__vocals/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a vocals audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Hollow Ground - Ill Fate__vocals
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Hollow Ground - Ill Fate__vocals/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Hollow Ground - Ill Fate__vocals/IRM1.wav
    Open-UMix: configs/resources/audio/Hollow Ground - Ill Fate__vocals/Open-UMix.wav
    REP1: configs/resources/audio/Hollow Ground - Ill Fate__vocals/REP1.wav
    SCNet-large: configs/resources/audio/Hollow Ground - Ill Fate__vocals/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Hollow Ground - Ill Fate__vocals/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Hollow Ground - Ill Fate__vocals/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a vocals audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Raft Monk - Tiring__vocals
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Raft Monk - Tiring__vocals/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Raft Monk - Tiring__vocals/IRM1.wav
    Open-UMix: configs/resources/audio/Raft Monk - Tiring__vocals/Open-UMix.wav
    REP1: configs/resources/audio/Raft Monk - Tiring__vocals/REP1.wav
    SCNet-large: configs/resources/audio/Raft Monk - Tiring__vocals/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Raft Monk - Tiring__vocals/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Raft Monk - Tiring__vocals/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a vocals audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: BKS - Too Much__vocals
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/BKS - Too Much__vocals/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/BKS - Too Much__vocals/IRM1.wav
    Open-UMix: configs/resources/audio/BKS - Too Much__vocals/Open-UMix.wav
    REP1: configs/resources/audio/BKS - Too Much__vocals/REP1.wav
    SCNet-large: configs/resources/audio/BKS - Too Much__vocals/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/BKS - Too Much__vocals/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/BKS - Too Much__vocals/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a vocals audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Tom McKenzie - Directions__vocals
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Tom McKenzie - Directions__vocals/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Tom McKenzie - Directions__vocals/IRM1.wav
    Open-UMix: configs/resources/audio/Tom McKenzie - Directions__vocals/Open-UMix.wav
    REP1: configs/resources/audio/Tom McKenzie - Directions__vocals/REP1.wav
    SCNet-large: configs/resources/audio/Tom McKenzie - Directions__vocals/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Tom McKenzie - Directions__vocals/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Tom McKenzie - Directions__vocals/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a vocals audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Bobby Nobody - Stitch Up__vocals
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Bobby Nobody - Stitch Up__vocals/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Bobby Nobody - Stitch Up__vocals/IRM1.wav
    Open-UMix: configs/resources/audio/Bobby Nobody - Stitch Up__vocals/Open-UMix.wav
    REP1: configs/resources/audio/Bobby Nobody - Stitch Up__vocals/REP1.wav
    SCNet-large: configs/resources/audio/Bobby Nobody - Stitch Up__vocals/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Bobby Nobody - Stitch Up__vocals/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Bobby Nobody - Stitch Up__vocals/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a vocals audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: James Elder & Mark M Thompson - The English Actor__vocals
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/James Elder Mark M Thompson - The English Actor__vocals/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/James Elder Mark M Thompson - The English Actor__vocals/IRM1.wav
    Open-UMix: configs/resources/audio/James Elder Mark M Thompson - The English Actor__vocals/Open-UMix.wav
    REP1: configs/resources/audio/James Elder Mark M Thompson - The English Actor__vocals/REP1.wav
    SCNet-large: configs/resources/audio/James Elder Mark M Thompson - The English Actor__vocals/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/James Elder Mark M Thompson - The English Actor__vocals/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/James Elder Mark M Thompson - The English Actor__vocals/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a vocals audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Louis Cressy Band - Good Time__vocals
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Louis Cressy Band - Good Time__vocals/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Louis Cressy Band - Good Time__vocals/IRM1.wav
    Open-UMix: configs/resources/audio/Louis Cressy Band - Good Time__vocals/Open-UMix.wav
    REP1: configs/resources/audio/Louis Cressy Band - Good Time__vocals/REP1.wav
    SCNet-large: configs/resources/audio/Louis Cressy Band - Good Time__vocals/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Louis Cressy Band - Good Time__vocals/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Louis Cressy Band - Good Time__vocals/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a vocals audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: Moosmusic - Big Dummy Shake__vocals
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/Moosmusic - Big Dummy Shake__vocals/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/Moosmusic - Big Dummy Shake__vocals/IRM1.wav
    Open-UMix: configs/resources/audio/Moosmusic - Big Dummy Shake__vocals/Open-UMix.wav
    REP1: configs/resources/audio/Moosmusic - Big Dummy Shake__vocals/REP1.wav
    SCNet-large: configs/resources/audio/Moosmusic - Big Dummy Shake__vocals/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/Moosmusic - Big Dummy Shake__vocals/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/Moosmusic - Big Dummy Shake__vocals/lpf_anchor.wav
  type: mushra
- content: This exercise is to evaluate the quality of a vocals audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: We Fell From The Sky - Not You__vocals
  name: MUSHRA
  randomize: true
  reference: configs/resources/audio/We Fell From The Sky - Not You__vocals/ref.wav
  showWaveform: true
  stimuli:
    IRM1: configs/resources/audio/We Fell From The Sky - Not You__vocals/IRM1.wav
    Open-UMix: configs/resources/audio/We Fell From The Sky - Not You__vocals/Open-UMix.wav
    REP1: configs/resources/audio/We Fell From The Sky - Not You__vocals/REP1.wav
    SCNet-large: configs/resources/audio/We Fell From The Sky - Not You__vocals/SCNet-large.wav
    htdemucs_ft: configs/resources/audio/We Fell From The Sky - Not You__vocals/htdemucs_ft.wav
    lpf_anchor: configs/resources/audio/We Fell From The Sky - Not You__vocals/lpf_anchor.wav
  type: mushra
- content: Thank you for participating in this listening test. Please click the button below to submit your responses.
  name: Thank you
  showResults: true
  type: finish
  writeResults: true
remoteService: service/write.php
showButtonPreviousPage: true
stopOnErrors: true
testId: mss
testname: MSS Subjective Evaluation
