bufferSize: 2048
pages:
- content: Thank you for taking part in this study as the part at the University of
    Amsterdam.<br>In this research, we will be performing an informal MUSHRA experiment
    to correlate subjective score of audio quality with objective measures. In musical
    source separation (MSS), an audio recording is broken into its constituent parts
    (eg guitar, singing, drums, bass). These extractions can have varying qualities
    as measured objectively and subjectively at odds with similar estimates. In other
    words, some extractions can have a high objective score and sound terrible, but
    others can have the opposite.<br>In this experiment, you will hear approximately
    25 different audio samples. The samples are of individual instruments (eg. guitar,
    drums, bass, or vocals). A reference (perfect 100 score) will be provided. In
    this test, please rate the other recordings from 0 (unintelligible, or complete
    task failure) to 100. The task should take approximately 15 minutes.<br>Please
    use your computer at a reasonable volume with headphones in a quiet listening
    environment.<br>When evaluating these extracts, compare them to the reference,
    which would warrant a 100% score. <br> Pay particular attention to whether the
    extract has other instruments that should not be present, interference, or noise.
    These should negatively affect the score.<br>Thanks, Noah Jaffe
  id: welcome_instructions
  name: Welcome to the musical source separation (MSS) evaluation task
  type: generic
- content: You will be participating in this research project on a voluntary basis.
    This means you are free to stop taking part at any stage. This will not have any
    consequences and you will not be obliged to finish the procedures described above.
    You can always decide to withdraw your consent later on. If you decide to stop
    or withdraw your consent, all the information gathered up until then will be permanently
    deleted.<br>I hereby declare that I have been clearly informed about the research
    project musical source separation perception at the University of Amsterdam, Faculty
    of Humanities, conducted by Noah Jaffe under supervision of J. A. Burgoyne as
    described in the information brochure. My questions have been answered to my satisfaction.<br>I
    realise that participation in this research is on an entirely voluntary basis.
    I retain the right to revoke this consent without having to provide any reasons
    for my decision. I am aware that I am entitled to discontinue the research at
    any time, and that I can always withdraw my consent after the research has ended.
    If I decide to stop or withdraw my consent, all the information gathered up until
    then will be permanently deleted.<br>I understand that no personal information
    will be collected.<br>If I need any further information on the research, now or
    in the future, I can contact J.A. Burgoyne (phone number +31 20 525 7034 e-mail
    j.a.burgoyne@uva.nl; Postbus 93058, 1099 BB Amsterdam.<br>If I have any complaints
    regarding this research, I can contact the secretary of the Ethics Committee of
    the Faculty of Humanities of the University of Amsterdam; email commissie- ethiek-fgw@uva.nl;
    phone number +31 20 525 3054; Kloveniersburgwal 48, 1012 CX Amsterdam.<br>By pressing
    Next I consent to participating in this research. Furthermore, I understand that
    I can revoke my consent by closing the web browser at any time prior to pressing
    Send Results on the final page.
  id: informed_consent
  mustConsent: true
  name: Informed Consent
  type: generic
- content: This exercise is to evaluate the quality of a vocals audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: trial12
  name: MUSHRA
  reference: configs/resources/audio/trial12/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial12/TAU1.wav
    C2: configs/resources/audio/trial12/IRM2.wav
    C3: configs/resources/audio/trial12/MWF.wav
    C4: configs/resources/audio/trial12/UHL3.wav
    C5: configs/resources/audio/trial12/TAK2.wav
    anchor35: configs/resources/audio/trial12/anchor35.wav
  type: mushra
- content: This exercise is to evaluate the quality of a bass audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: trial27
  name: MUSHRA
  reference: configs/resources/audio/trial27/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial27/TAU1.wav
    C2: configs/resources/audio/trial27/IRM2.wav
    C3: configs/resources/audio/trial27/MWF.wav
    C4: configs/resources/audio/trial27/UHL3.wav
    C5: configs/resources/audio/trial27/TAK2.wav
    anchor35: configs/resources/audio/trial27/anchor35.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: false
  createAnchor70: false
  enableLooping: true
  id: trial32
  name: MUSHRA
  reference: configs/resources/audio/trial32/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial32/TAU1.wav
    C2: configs/resources/audio/trial32/IRM2.wav
    C3: configs/resources/audio/trial32/MWF.wav
    C4: configs/resources/audio/trial32/UHL3.wav
    C5: configs/resources/audio/trial32/TAK2.wav
    anchor35: configs/resources/audio/trial32/anchor35.wav
  type: mushra
