bufferSize: 2048
pages:
- content: "Thank you for taking part in this study as the part at the University\
    \ of Amsterdam.<br>In this research, we will be performing an informal MUSHRA\
    \ experiment to correlate subjective score of audio quality with objective measures.\
    \ In musical source separation (MSS), an audio recording is broken into its constituent\
    \ parts (eg guitar, singing, drums, bass). These extractions can have varying\
    \ qualities as measured objectively and subjectively\u2014at odds with similar\
    \ extractions. In other words, some extractions can have a high objective score\
    \ and sound terrible, but others can have the opposite.<br>In this experiment,\
    \ you will hear approximately 25 different audio samples. The samples are of individual\
    \ instruments (eg. guitar, drums, bass, or vocals). A reference (perfect 100 score)\
    \ will be provided. In this test, please rate the other recordings from 0 (unintelligible,\
    \ or complete task failure) to 100. The task should take approximately 15 minutes.<br><br><br>Please\
    \ use your computer at a reasonable volume with headphones in a quiet listening\
    \ environment.<br>When evaluating these extracts, compare them to the reference,\
    \ which would warrant a 100% score. <br> Pay particular attention to whether the\
    \ extract has other instruments that should not be present, interference, or noise.\
    \ These should negatively affect the score. <br>Thanks, Noah Jaffe"
  id: welcome_instructions
  name: Welcome to the musical source separation (MSS) evaluation task
  type: generic
- content: "You will be participating in this research project on a voluntary basis.\
    \ This means you are free to stop taking part at any stage. This will not have\
    \ any consequences and you will not be obliged to finish the procedures described\
    \ above. You can always decide to withdraw your consent later on. If you decide\
    \ to stop or withdraw your consent, all the information gathered up until then\
    \ will be permanently deleted.<br>I hereby declare that I have been clearly informed\
    \ about the research project musical source separation perception at the University\
    \ of Amsterdam, Faculty of Humanities, conducted by Jaffe under supervision of\
    \ J. A. Burgoyne as described in the information brochure. My questions have been\
    \ answered to my satisfaction.<br>I realise that participation in this research\
    \ is on an entirely voluntary basis. I retain the right to revoke this consent\
    \ without having to provide any reasons for my decision. I am aware that I am\
    \ entitled to discontinue the research at any time, and that I can always withdraw\
    \ my consent after the research has ended. If I decide to stop or withdraw my\
    \ consent, all the information gathered up until then will be permanently deleted.<br>I\
    \ understand that no personal information will be collected.<br>If I need any\
    \ further information on the research, now or in the future, I can contact J.A.\
    \ Burgoyne (phone number +31 20 \u2013 525 7034 e-mail j.a.burgoyne@uva.nl; Postbus\
    \ 93058, 1099 BB Amsterdam.<br>If I have any complaints regarding this research,\
    \ I can contact the secretary of the Ethics Committee of the Faculty of Humanities\
    \ of the University of Amsterdam; email commissie- ethiek-fgw@uva.nl; phone number\
    \ +31 20 \u2013 525 3054; Kloveniersburgwal 48, 1012 CX Amsterdam.<br>By pressing\
    \ Next I consent to participating in this research. Furthermore, I understand\
    \ that I can revoke my consent by closing the web browser at any time prior to\
    \ pressing \u201CSend Results\u201D on the final page."
  id: informed_consent
  mustConsent: true
  name: Informed Consent
  type: generic
- content: This exercise is to evaluate the quality of a accomp audio estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial3
  name: MUSHRA
  reference: configs/resources/audio/trial3/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial3/2DFT.wav
    C2: configs/resources/audio/trial3/HPLP.wav
    C3: configs/resources/audio/trial3/REP2.wav
    C4: configs/resources/audio/trial3/TAU1.wav
    C5: configs/resources/audio/trial3/IRM2.wav
  type: mushra
- content: This exercise is to evaluate the quality of a vocals audio estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial8
  name: MUSHRA
  reference: configs/resources/audio/trial8/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial8/TAU1.wav
    C2: configs/resources/audio/trial8/IRM2.wav
    C3: configs/resources/audio/trial8/MWF.wav
    C4: configs/resources/audio/trial8/UHL3.wav
    C5: configs/resources/audio/trial8/TAK2.wav
    C6: configs/resources/audio/trial8/2DFT.wav
  type: mushra
- content: This exercise is to evaluate the quality of a accomp audio estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial13
  name: MUSHRA
  reference: configs/resources/audio/trial13/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial13/TAU1.wav
    C2: configs/resources/audio/trial13/IRM2.wav
    C3: configs/resources/audio/trial13/MWF.wav
    C4: configs/resources/audio/trial13/UHL3.wav
    C5: configs/resources/audio/trial13/TAK2.wav
  type: mushra
- content: This exercise is to evaluate the quality of a accomp audio estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial18
  name: MUSHRA
  reference: configs/resources/audio/trial18/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial18/TAU1.wav
    C2: configs/resources/audio/trial18/IRM2.wav
    C3: configs/resources/audio/trial18/MWF.wav
    C4: configs/resources/audio/trial18/UHL3.wav
    C5: configs/resources/audio/trial18/TAK2.wav
  type: mushra
- content: This exercise is to evaluate the quality of a bass audio estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial23
  name: MUSHRA
  reference: configs/resources/audio/trial23/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial23/TAU1.wav
    C2: configs/resources/audio/trial23/IRM2.wav
    C3: configs/resources/audio/trial23/MWF.wav
    C4: configs/resources/audio/trial23/UHL3.wav
  type: mushra
- content: This exercise is to evaluate the quality of a bass audio estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial28
  name: MUSHRA
  reference: configs/resources/audio/trial28/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial28/TAU1.wav
    C2: configs/resources/audio/trial28/IRM2.wav
    C3: configs/resources/audio/trial28/MWF.wav
    C4: configs/resources/audio/trial28/UHL3.wav
    C5: configs/resources/audio/trial28/TAK2.wav
  type: mushra
- content: This exercise is to evaluate the quality of a drums audio estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial33
  name: MUSHRA
  reference: configs/resources/audio/trial33/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial33/TAU1.wav
    C2: configs/resources/audio/trial33/IRM2.wav
    C3: configs/resources/audio/trial33/MWF.wav
    C4: configs/resources/audio/trial33/UHL3.wav
    C5: configs/resources/audio/trial33/TAK2.wav
  type: mushra
- content: This exercise is to evaluate the quality of a guitar/keyboard/other audio
    estimate.
  createAnchor35: true
  createAnchor70: true
  enableLooping: true
  id: trial38
  name: MUSHRA
  reference: configs/resources/audio/trial38/ref.wav
  showWaveform: true
  stimuli:
    C1: configs/resources/audio/trial38/TAU1.wav
    C2: configs/resources/audio/trial38/IRM2.wav
    C3: configs/resources/audio/trial38/MWF.wav
    C4: configs/resources/audio/trial38/UHL3.wav
    C5: configs/resources/audio/trial38/TAK2.wav
  type: mushra
remoteService: service/write.php
showButtonPreviousPage: true
stopOnErrors: true
testId: mss
testname: MSS Subjective Evaluation
