testname: Noah MSS
testId: mss
bufferSize: 2048
stopOnErrors: true
showButtonPreviousPage: true
remoteService: service/write.php


pages:
    - type: generic
      id: first_page
      name: Welcome
      content: Welcome to webMUSHRA! ERB Statements to go here!!!
    - type: mushra
      id: trial1
      name: MUSHRA
      content: This training shows how to use our user interface. Please perform the underlined instructions to proceed with the training session. Reminder: In a MUSHRA listening test you are asked to rate the Basic Audio Quality (BAQ) of each condition.<br/>Basic Audio Quality is a single and global attribute that is used to judge any and all detected differences between the reference and the condition.
      showWaveform: true
      enableLooping: true
      reference: configs/resources/audio/1/ref.wav
      createAnchor35: true
      createAnchor70: true
      stimuli:
          C1: configs/resources/audio/1/2dft.wav
          C2: configs/resources/audio/1/hplp.wav
          C3: configs/resources/audio/1/irm2.wav
          C4: configs/resources/audio/1/rep2.wav
          C5: configs/resources/audio/1/tau1.wav
    -
          - random
          - type: mushra
            id: trial_random_1
            name: MUSHRA - Random 2
            content: Due to randomization, this page will be either the second MUSHRA page or the third MUSHRA page.
            enableLooping: true
            reference: configs/resources/audio/1/ref.wav
            createAnchor35: false
            createAnchor70: false
            stimuli:
                C1: configs/resources/audio/1/2dft.wav
                C2: configs/resources/audio/1/hplp.wav
                C3: configs/resources/audio/1/irm2.wav          

    - type: finish
      name: Thank you
      content: Thank you for attending!
      showResults: true
      writeResults: true
